Documented pip hacks required to get a viable virtual environment
As if this commit connection fails on the line:
ret = instance._bus.con.call_sync(
with an error message
gi.repository.GLib.GError: g-io-error-quark: GDBus.Error:org.bluez.Error.Failed: br-connection-unknown (36)